INSERT INTO Employee(id,name,age) VALUES (nextval('hibernate_sequence'),'Mango',15);
INSERT INTO Employee(id,name,age) VALUES (nextval('hibernate_sequence'),'Strawberry',16);
INSERT INTO Employee(id,name,age) VALUES (nextval('hibernate_sequence'),'Orange',17);
INSERT INTO Employee(id,name,age) VALUES (nextval('hibernate_sequence'),'Lemon',1);
INSERT INTO Employee(id,name,age) VALUES (nextval('hibernate_sequence'),'Blueberry',5);
INSERT INTO Employee(id,name,age) VALUES (nextval('hibernate_sequence'),'Banana',7);
INSERT INTO Employee(id,name,age) VALUES (nextval('hibernate_sequence'),'Watermelon',8);
INSERT INTO Employee(id,name,age) VALUES (nextval('hibernate_sequence'),'Apple',99);
INSERT INTO Employee(id,name,age) VALUES (nextval('hibernate_sequence'),'Pear',88);